<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [RegressionSuite]" duration-ms="64355" started-at="2023-04-13T16:54:04 IST" finished-at="2023-04-13T16:55:08 IST">
    <groups>
      <group name="sanity">
        <method signature="TC002_Login_Test.verifyLogin()[pri:0, instance:testCases.TC002_Login_Test@2e3fc542]" name="verifyLogin" class="testCases.TC002_Login_Test"/>
      </group> <!-- sanity -->
      <group name="master">
        <method signature="TC002_Login_Test.verifyLogin()[pri:0, instance:testCases.TC002_Login_Test@2e3fc542]" name="verifyLogin" class="testCases.TC002_Login_Test"/>
      </group> <!-- master -->
    </groups>
    <test name="OpenCartTest(failed)" duration-ms="64355" started-at="2023-04-13T16:54:04 IST" finished-at="2023-04-13T16:55:08 IST">
      <class name="testCases.TC002_Login_Test">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:testCases.TC002_Login_Test@2e3fc542]" name="setUp" is-config="true" duration-ms="43041" started-at="2023-04-13T16:54:04 IST" finished-at="2023-04-13T16:54:47 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyLogin()[pri:0, instance:testCases.TC002_Login_Test@2e3fc542]" name="verifyLogin" duration-ms="19503" started-at="2023-04-13T16:54:47 IST" finished-at="2023-04-13T16:55:07 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid login Details expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid login Details expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at testCases.TC002_Login_Test.verifyLogin(TC002_Login_Test.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testCases.TC002_Login_Test@2e3fc542]" name="tearDown" is-config="true" duration-ms="0" started-at="2023-04-13T16:55:08 IST" finished-at="2023-04-13T16:55:08 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC002_Login_Test -->
    </test> <!-- OpenCartTest(failed) -->
  </suite> <!-- Failed suite [RegressionSuite] -->
</testng-results>
